"use client";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { Providers } from "./providers";
import { getCookie } from "./helpers/apiHelper";
import "./globals.css";
import StartUp from "./startup/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isLogged, setIsLogged] = useState(false);

  const getToken = async () => {
    const token = await getCookie("token");
    if (token) {
      setIsLogged(true);
    }
  };

  useEffect(() => {
    getToken();
  }, [isLogged]);

  return (
    <html lang="es">
      {!isLogged && (
        <StartUp inter={inter} providers={Providers}>
          {children}
        </StartUp>
      )}
      {isLogged && children}
    </html>
  );
}
