"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { Providers } from "./providers";
import { getCookie } from "./helpers/apiHelper";
import { Skeleton } from "@nextui-org/react";
import StartUp from "./startup/page";
import HomePage from "./homePage/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Index({ children }) {
  const [isLoading, setIsLoading] = useState(true);
  const [isLogged, setIsLogged] = useState(false);

  const getToken = async () => {
    const token = await getCookie("token");
    if (token) {
      setIsLoading(false);
      setIsLogged(true);
    }
  };

  useEffect(() => {
    getToken();
    if (!isLogged) {
      setIsLoading(false);
    }
  }, [isLogged]);

  let contentToRender;

  if (isLoading) {
    contentToRender = <Skeleton className="flex h-screen w-screen" />;
  } else if (!isLoading && !isLogged) {
    contentToRender = (
      <StartUp inter={inter} providers={Providers}>
        {children}
      </StartUp>
    );
  } else if (isLogged) {
    contentToRender = (
      <HomePage isLogged={isLogged} setIsLogged={setIsLogged} />
    );
  }

  return contentToRender;
}
